package Controller.Views;

import Entity.Staff;
import Service.StaffService;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

import java.net.URL;
import java.time.LocalDate;
import java.util.ResourceBundle;

/**
 * Controller for the Staff management view. Handles staff data display, adding new staff members,
 * filtering staff list, and navigating to the Dashboard.
 * Interacts with the StaffService to perform CRUD operations.
 */
public class StaffViewController implements Initializable {
    @FXML private TextField firstNameField;
    @FXML private TextField lastNameField;
    @FXML private ComboBox<String> roleComboBox;
    @FXML private TextField emailField;
    @FXML private TextField phoneField;
    @FXML private DatePicker hireDatePicker;
    @FXML private TextField searchField;

    @FXML private TableView<Staff> staffTable;
    @FXML private TableColumn<Staff, Integer> idColumn;
    @FXML private TableColumn<Staff, String> firstNameColumn;
    @FXML private TableColumn<Staff, String> lastNameColumn;
    @FXML private TableColumn<Staff, String> roleColumn;
    @FXML private TableColumn<Staff, String> emailColumn;
    @FXML private TableColumn<Staff, String> phoneColumn;
    @FXML private TableColumn<Staff, LocalDate> hireDateColumn;

    private final StaffService staffService = new StaffService();
    private final ObservableList<Staff> staffList = FXCollections.observableArrayList();

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // Initialize role combo box
        roleComboBox.setItems(FXCollections.observableArrayList(
                "Librarian", "Assistant Librarian", "Administrator"
        ));

        // Initialize table columns
        idColumn.setCellValueFactory(new PropertyValueFactory<>("staffId"));
        firstNameColumn.setCellValueFactory(new PropertyValueFactory<>("firstName"));
        lastNameColumn.setCellValueFactory(new PropertyValueFactory<>("lastName"));
        roleColumn.setCellValueFactory(new PropertyValueFactory<>("role"));
        emailColumn.setCellValueFactory(new PropertyValueFactory<>("email"));
        phoneColumn.setCellValueFactory(new PropertyValueFactory<>("phoneNumber"));
        hireDateColumn.setCellValueFactory(new PropertyValueFactory<>("hireDate"));

        // Setup search functionality
        searchField.textProperty().addListener((observable, oldValue, newValue) -> {
            filterStaff(newValue);
        });

        // Load initial data
        refreshTable();
    }

    /**
     * Handles the action of adding a new staff member.
     * Collects data from the input fields and calls the StaffService to add the new staff.
     * Displays an alert with the result.
     */
    @FXML
    private void handleAddStaff() {
        try {
            // Check for empty required fields
            if (firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty() || roleComboBox.getValue() == null ||
                    emailField.getText().isEmpty() || phoneField.getText().isEmpty() || hireDatePicker.getValue() == null) {
                throw new IllegalArgumentException("Please fill in all required fields.");
            }

            // Create new staff object with password optional
            Staff staff = new Staff(
                    0, // ID will be generated by database
                    firstNameField.getText(),
                    lastNameField.getText(),
                    roleComboBox.getValue(),
                    emailField.getText(),
                    phoneField.getText(),
                    hireDatePicker.getValue(),
                    "" // Placeholder password; you might need a password input field for this
            );

            staffService.addStaff(staff);
            refreshTable();
            clearFields();
            showAlert(Alert.AlertType.INFORMATION, "Success", "Staff member added successfully!");
        } catch (IllegalArgumentException e) {
            showAlert(Alert.AlertType.ERROR, "Error", e.getMessage());
        }
    }

    /**
     * Clears the input fields for adding a new staff member.
     */
    @FXML
    private void handleClear() {
        clearFields();
    }

    /**
     * Filters the staff list based on the search text entered in the search field.
     * Updates the table view to display matching staff records.
     *
     * @param searchText the text to filter the staff list
     */
    private void filterStaff(String searchText) {
        ObservableList<Staff> filteredList = FXCollections.observableArrayList();
        if (searchText == null || searchText.isEmpty()) {
            staffTable.setItems(staffList);
        } else {
            String lowerCaseFilter = searchText.toLowerCase();
            staffList.forEach(staff -> {
                if (staff.getFirstName().toLowerCase().contains(lowerCaseFilter) ||
                        staff.getLastName().toLowerCase().contains(lowerCaseFilter) ||
                        staff.getEmail().toLowerCase().contains(lowerCaseFilter)) {
                    filteredList.add(staff);
                }
            });
            staffTable.setItems(filteredList);
        }
    }

    /**
     * Clears all the input fields in the view.
     */
    private void clearFields() {
        firstNameField.clear();
        lastNameField.clear();
        roleComboBox.setValue(null);
        emailField.clear();
        phoneField.clear();
        hireDatePicker.setValue(null);
    }

    /**
     * Refreshes the staff table by fetching the latest list of staff members
     * from the StaffService and updating the table view.
     */
    private void refreshTable() {
        staffList.clear();
        staffList.addAll(staffService.getAllStaff());
        staffTable.setItems(staffList);
    }

    /**
     * Displays an alert with a specified type, title, and content.
     *
     * @param type the type of alert (e.g., Information, Error)
     * @param title the title of the alert
     * @param content the content text of the alert
     */
    private void showAlert(Alert.AlertType type, String title, String content) {
        Alert alert = new Alert(type);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(content);
        alert.showAndWait();
    }

    /**
     * Handles the navigation back to the Dashboard view.
     * Switches the current scene to the Dashboard view.
     */
    @FXML
    public void handleBackToDashboard() {
        try {
            // Get the current stage (window)
            Stage stage = (Stage) firstNameField.getScene().getWindow();

            // Load the Dashboard view
            FXMLLoader loader = new FXMLLoader(getClass().getResource("/org/example/librarymanagementsys/DashboardView.fxml"));
            Parent root = loader.load();

            // Create a new scene and set it on the stage
            Scene scene = new Scene(root);
            scene.getStylesheets().add(getClass().getResource("/org/example/librarymanagementsys/dashboard.css").toExternalForm());

            stage.setScene(scene);  // Switch to the new scene
            stage.show();  // Display the new scene

        } catch (Exception e) {
            showAlert(Alert.AlertType.ERROR, "Error", "Navigation Error");
            e.printStackTrace();
        }
    }
}
